In [21]:
import numpy as np
A = np.array([[0,0,1,1],
              [0,3,1,-7],
              [2,7,6,1],
              [1,2,2,1]])
A_inv = np.linalg.inv(A) # Обратная матрица
print(A_inv)

[[-0.46666667  0.2        -0.86666667  2.73333333]
 [-0.86666667 -0.2         0.53333333 -1.06666667]
 [ 1.2         0.2        -0.2         0.4       ]
 [-0.2        -0.2         0.2        -0.4       ]]


In [15]:
print(np.linalg.det(A)) # Определитель матрицы

15.0


In [16]:
from numpy.linalg import matrix_rank
print(matrix_rank(A))                # Ранг матрицы

4


In [23]:
A = np.array([[1, 2, 3], [4, 2, 1], [1, 0, 1]])
B = np.array([[1, 2, 1], [1, -1, 2], [1, 2, 1]])
C = np.array([[2,2], [1, 4]])
D = np.array([[3, 1], [2, 1], [-1, 2]])
E = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
G = np.array([[1, 1, 2, 3], [4, 2, 1, 3], [2, 1, 2, 3], [1, 2, 5, 4]])

In [26]:
print(-3 * C, '\n')
print(-A + 2 * B - 3 * E, '\n')
print(A.transpose(), '\n') # Транспонирую матрицу
print(np.linalg.det(C), '\n')   # Определитель матрицы
print(np.linalg.det(A), '\n')
print(np.linalg.det(G), '\n')
print(np.linalg.inv(A), '\n')
print(np.dot(A, np.linalg.inv(A)).sum(), '\n') # Сумма элементов произведения матрицы
                                                # и обратной матрицы
print(np.dot(A, B), '\n',) # Произведение матриц

[[ -6  -6]
 [ -3 -12]] 

[[-2  2 -1]
 [-2 -7  3]
 [ 1  4 -2]] 

[[1 4 1]
 [2 2 0]
 [3 1 1]] 

[[ 3  2 -1]
 [ 1  1  2]] 

6.0 

-9.999999999999998 

8.999999999999998 

[[-0.2  0.2  0.4]
 [ 0.3  0.2 -1.1]
 [ 0.2 -0.2  0.6]] 

3.0 

[[6 6 8]
 [7 8 9]
 [2 4 2]] 

