In [38]:
import numpy as np
from numpy.linalg import matrix_rank

###  Алгебраические действия с матрицами

In [23]:
A = np.array([[1, 2, 3], [4, 2, 1], [1, 0, 1]])
B = np.array([[1, 2, 1], [1, -1, 2], [1, 2, 1]])
C = np.array([[2,2], [1, 4]])
D = np.array([[3, 1], [2, 1], [-1, 2]])
E = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
G = np.array([[1, 1, 2, 3], [4, 2, 1, 3], [2, 1, 2, 3], [1, 2, 5, 4]])

In [26]:
print(-3 * C, '\n')
print(-A + 2 * B - 3 * E, '\n')
print(A.transpose(), '\n') # Транспонирую матрицу
print(np.linalg.det(C), '\n')   # Определитель матрицы
print(matrix_rank(A))                # Ранг матрицы
print(np.linalg.det(A), '\n')
print(np.linalg.det(G), '\n')
print(np.linalg.inv(A), '\n')
print(np.dot(A, np.linalg.inv(A)).sum(), '\n') # Сумма элементов произведения матрицы
                                                # и обратной матрицы
print(np.dot(A, B), '\n',) # Произведение матриц

[[ -6  -6]
 [ -3 -12]] 

[[-2  2 -1]
 [-2 -7  3]
 [ 1  4 -2]] 

[[1 4 1]
 [2 2 0]
 [3 1 1]] 

[[ 3  2 -1]
 [ 1  1  2]] 

6.0 

-9.999999999999998 

8.999999999999998 

[[-0.2  0.2  0.4]
 [ 0.3  0.2 -1.1]
 [ 0.2 -0.2  0.6]] 

3.0 

[[6 6 8]
 [7 8 9]
 [2 4 2]] 



### Решение системы уравнений
4 * x1 + 2 * x2 - x3 = 0;

x1 + 2 * x2 + x3 = 1;

x2 - x3 = -3;

In [61]:
A = np.array([[4, 2, -1],
              [1, 2, 1],
              [0, 1, -1]])

b = np.array([0, 1, -3])

print(np.linalg.solve(A, b))  # Получили три корня

[ 1. -1.  2.]
